import type { ReferenceStyle } from "@/types"

export const REFERENCE_STYLES: ReferenceStyle[] = [
  {
    id: "dimensional-brushed",
    name: "Dimensional Brushed Metal",
    description: "Deep-set letters with brushed aluminum finish, stand-off mounting",
    imageUrl: "/references/dimensional-brushed.jpg",
    lightingType: "front",
    materialFeel: "brushed-metal",
    depthStyle: "deep",
    mountingStyle: "stand-off",
    hasBackingPlate: false,
    compatibleLightModes: ["front"],
  },
  {
    id: "backlit-acrylic",
    name: "Backlit Acrylic Glow",
    description: "Halo-lit letters with smooth acrylic face, warm ambient glow",
    imageUrl: "/references/backlit-acrylic.jpg",
    lightingType: "back",
    materialFeel: "acrylic",
    depthStyle: "shallow",
    mountingStyle: "stand-off",
    hasBackingPlate: false,
    compatibleLightModes: ["back", "both"],
  },
  {
    id: "flat-cut-backing",
    name: "Flat Cut with Backing Plate",
    description: "Clean flat letters on a contrasting backing panel, modern retail look",
    imageUrl: "/references/flat-cut-backing.jpg",
    lightingType: "front",
    materialFeel: "flat",
    depthStyle: "flat",
    mountingStyle: "flush",
    hasBackingPlate: true,
    compatibleLightModes: ["front"],
  },
  {
    id: "neon-dimensional",
    name: "Neon Dimensional",
    description: "Bold 3D letters with exposed neon tube edges, high-energy street presence",
    imageUrl: "/references/neon-dimensional.jpg",
    lightingType: "both",
    materialFeel: "neon",
    depthStyle: "deep",
    mountingStyle: "raceway",
    hasBackingPlate: true,
    compatibleLightModes: ["front", "back", "both"],
  },
  {
    id: "premium-dimensional",
    name: "Premium Dimensional Dark",
    description: "Deep matte black dimensional letters, subtle front light, luxury feel",
    imageUrl: "/references/premium-dimensional.jpg",
    lightingType: "front",
    materialFeel: "dimensional",
    depthStyle: "deep",
    mountingStyle: "stand-off",
    hasBackingPlate: false,
    compatibleLightModes: ["front", "both"],
  },
]
